# Filtered summary data from ag_ab dataframe
--> to only download pdb files we actually need and want and not all of them

import pandas as pd
import os.path

# path to dataframe
df = pd.read_csv("../data/ab_ag.tsv", sep="\t")
df

# make a cop of the original so df stays unchanged
df_copy = df.copy()

# Nur die gewünschten Spalten behalten
df_filtered = df_copy[["pdb", "Hchain", "Lchain", "model", "antigen_chain",
                        "antigen_type", "antigen_name", "compound", "organism",
                        "heavy_species", "light_species", "antigen_species",
                        "resolution", "method", "scfv", "engineered", 
                        "heavy_subclass", "light_subclass", "light_ctype"]]

print(df_filtered.shape)

#alle Zeilen in denen NaN vorkommt entfernen 
df_filtered = df_filtered.dropna(subset=["pdb", "Hchain", "Lchain", 
                                        "model", "antigen_chain", "antigen_type",
                                        "antigen_species", "method"])
                                 
print(df_filtered.shape)


# Nur klassische Antikörper (nicht scFv) behalten
df_filtered = df_filtered[df_filtered["scfv"]== False]

# Zuerst sicherstellen, dass die Spalte 'resolution' numerisch ist
df_filtered['resolution'] = pd.to_numeric(df_filtered["resolution"], errors='coerce')

# nur Zeilen behalten, deren resolution <=3.0 ist
df_filtered = df_filtered[df_filtered["resolution"] <=3.0]

df_filtered


# Alle eindeutigen PDB-IDs aus der Spalte 'pdb' holen (ohne nochmal klein zu machen)
pdb_ids = df_filtered['pdb'].unique().tolist()

#save to file
pd.Series(pdb_ids).to_csv("pdb_ids.csv", index=False)

In [8]:
import pandas as pd
import os.path

# path to dataframe
df = pd.read_csv("../data/ab_ag.tsv", sep="\t")

df_filtered= (df
                .assign(resolution = pd.to_numeric(df["resolution"], errors='coerce'))
                .get(["pdb", "Hchain", "Lchain", "model", "antigen_chain",
                        "antigen_type", "antigen_name", "compound", "organism",
                        "heavy_species", "light_species", "antigen_species",
                        "resolution", "method", "scfv", "engineered", 
                        "heavy_subclass", "light_subclass", "light_ctype"])
                .dropna(subset=["pdb", "Hchain", "Lchain", 
                                "model", "antigen_chain", "antigen_type",
                                "antigen_species", "method"])
                .query("scfv== False and resolution <= 3.25 and antigen_type == 'protein'")
                .groupby("pdb")
                .head(1))

df_filtered.shape

(1489, 19)

In [9]:
df_filtered["species"] = ""
df_filtered.loc[df_filtered["antigen_species"].str.contains("coronavirus2", case = False, na = False), "species"] = "SARS-CoV-2"
df_filtered.loc[df_filtered["antigen_species"].str.contains("homo sapiens", case = False, na = False), "species"] = "Homo Sapiens"
df_filtered.loc[df_filtered["antigen_species"].str.contains("influenza a", case = False, na = False), "species"] = "Influenza A"
df_filtered = df_filtered[df_filtered["species"] != ""]

df_filtered.species.value_counts()

df_filtered.shape

(966, 20)

In [10]:
df_filtered.antigen_chain.unique()

array(['E', 'A', 'D', 'B', 'C', 'R', 'H', 'I', 'P', 'F', 'X', 'K', 'Z',
       'J', 'Q', 'T', 'G', 'M', 'V', 'S', 'c', 'Y', 'U', 'm', 'b', 'N',
       'O', 'W'], dtype=object)

In [11]:
os.makedirs("../generated/data cleanup", exist_ok=True)
df_filtered.to_csv("../generated/data cleanup/ab_ag_filtered_pdb.tsv", sep="\t", index = False)

## Pdb Liste mit eindeutigen pdbs für Sars CoV 2 (Corona)

In [12]:
# Alle eindeutigen PDB-IDs aus der gefilterten DataFrame holen
pdb_ids_sars_cov2 = df_filtered.query("species == 'SARS-CoV-2'").get(['pdb'])

#save to file
pdb_ids_sars_cov2.to_csv("pdb_ids_sars_cov2.csv", index=False, header=True)

pdb_ids_sars_cov2

       pdb
46    9cci
47    9ccj
52    9bj2
53    9bj3
108   8z6r
...    ...
5470  7chp
5482  7n4i
5511  7l7d
5514  7n3d
5522  7tas

[468 rows x 1 columns]

## Pdb Liste mit eindeutigen pdbs für Homo Sapiens

In [13]:
# Alle eindeutigen PDB-IDs aus der gefilterten DataFrame holen
pdb_ids_homo_sapiens = df_filtered.query("species == 'Homo Sapiens'").get(['pdb'])

#save to file
pdb_ids_homo_sapiens.to_csv("pdb_ids_homo_sapiens.csv", index=False, header=True)

pdb_ids_homo_sapiens

       pdb
29    8rmx
31    8rmy
128   8znz
144   9avo
145   9awe
...    ...
5515  4od2
5516  7rp3
5517  3q1s
5518  4zfg
5521  4ps4

[399 rows x 1 columns]

## Pdb Liste mit eindeutigen pdbs für Influenza A

In [14]:
# Alle eindeutigen PDB-IDs aus der gefilterten DataFrame holen
pdb_ids_influenza = df_filtered.query("species == 'Influenza A'").get(['pdb'])

#save to file
pdb_ids_influenza.to_csv("pdb_ids_influenza.csv", index=False, header=True)

pdb_ids_influenza

       pdb
5     8veb
8     8ved
11    8vee
14    8vef
20    9dpc
...    ...
5352  4kvn
5366  5vag
5391  4hfu
5396  6lxi
5433  5w6g

[99 rows x 1 columns]