In [41]:
#Daten importieren
import pandas as pd
df = pd.read_csv("../data/ab_ag.tsv", sep="\t")

#dimension
print(df.shape)

#zeigen welche spalten es gibt
print(df.columns)

(5523, 30)
Index(['pdb', 'Hchain', 'Lchain', 'model', 'antigen_chain', 'antigen_type',
       'antigen_het_name', 'antigen_name', 'short_header', 'date', 'compound',
       'organism', 'heavy_species', 'light_species', 'antigen_species',
       'authors', 'resolution', 'method', 'r_free', 'r_factor', 'scfv',
       'engineered', 'heavy_subclass', 'light_subclass', 'light_ctype',
       'affinity', 'delta_g', 'affinity_method', 'temperature', 'pmid'],
      dtype='object')

In [42]:
# Nur die gewünschten Spalten behalten
df_cleaned = df[["pdb",	"Hchain", "Lchain", "antigen_species", "heavy_subclass", "light_subclass", "antigen_type", "antigen_name", "organism", "resolution", "light_ctype"]]

#zeilen die noch übrig sind
print(df_cleaned.columns)

Index(['pdb', 'Hchain', 'Lchain', 'antigen_species', 'heavy_subclass',
       'light_subclass', 'antigen_type', 'antigen_name', 'organism',
       'resolution', 'light_ctype'],
      dtype='object')

In [43]:
#alle Zeilen in denen NaN vorkommt entfernen 
df_cleaned = df_cleaned.dropna()

#zum überprüfen
print("Vorher:", len(df))
print("Nachher:", len(df_cleaned))

Vorher: 5523
Nachher: 5257

In [44]:
#dimension anschauen
print(df_cleaned.shape)

(5257, 11)

In [45]:
# Zuerst sicherstellen, dass die Spalte 'resolution' numerisch ist
df_cleaned['resolution'] = pd.to_numeric(df_cleaned['resolution'], errors='coerce')

# Step 1: Dann nur Zeilen mit resolution <= 3.0 behalten
df_cleaned = df_cleaned[df_cleaned['resolution'] <= 3.0]

#dimension anschauen
print(df_cleaned.shape)

(2799, 11)

In [46]:
#Step 2: was gibt es alles in der Spalte Antigen typen
print(df_cleaned['antigen_type'].value_counts())
#keine weiter filterung notwendig

antigen_type
protein                        2523
protein | protein               217
protein | protein | protein      28
protein | peptide                14
peptide | protein                 7
peptide                           6
protein | protein | peptide       2
peptide | protein | protein       1
protein | peptide | protein       1
Name: count, dtype: int64

In [50]:
# Step 3: Entferne Zeilen mit fehlender Hchain, Lchain oder antigen_name
#wurde davor schon durch NaN entfernt

df_cleaned.head()

,pdb,Hchain,Lchain,antigen_species,heavy_subclass,light_subclass,antigen_type,antigen_name,organism,resolution,light_ctype
3,8uzp,H,L,mus musculus,IGHV1,IGLV1,protein,stem_mimetic_01,Homo sapiens; Mus musculus,2.711,Lambda
4,8uzp,A,B,mus musculus,IGHV1,IGLV1,protein,stem_mimetic_01,Homo sapiens; Mus musculus,2.711,Lambda
5,8veb,G,I,influenza a virus,IGHV4,IGKV1,protein,hemagglutinin,Homo sapiens; Influenza A virus,2.970,Kappa
6,8veb,H,L,influenza a virus,IGHV4,IGKV1,protein,hemagglutinin,Homo sapiens; Influenza A virus,2.970,Kappa
8,8ved,H,L,influenza a virus,IGHV4,IGKV2,protein,hemagglutinin,Homo sapiens; Influenza A virus,2.980,Kappa

In [48]:
# Steop 4: remove redundant structures

# Alle eindeutigen PDB-IDs aus der Spalte 'pdb' holen (ohne nochmal klein zu machen)
pdb_ids = df_cleaned['pdb'].unique().tolist()

print(f"Es sind {len(pdb_ids)} einzigartige PDB-IDs zum Herunterladen.")

Es sind 1480 einzigartige PDB-IDs zum Herunterladen.

In [49]:
from Bio.PDB import PDBList
import os

pdbl = PDBList()

# Ordner, in dem die PDB-Dateien gespeichert werden sollen
download_folder = "../data/pdb_files"

# Ordner erstellen, falls nicht vorhanden
os.makedirs(download_folder, exist_ok=True)

# Alle PDB-Dateien herunterladen
for pdb_id in pdb_ids:
    print(f"Lade PDB {pdb_id} herunter...")
    pdbl.retrieve_pdb_file(pdb_id, pdir=download_folder, file_format='pdb')

Lade PDB 8uzp herunter...
Structure exists: '../data/pdb_files/pdb8uzp.ent'
Lade PDB 8veb herunter...
Structure exists: '../data/pdb_files/pdb8veb.ent'
Lade PDB 8ved herunter...
Structure exists: '../data/pdb_files/pdb8ved.ent'
Lade PDB 9dpc herunter...
Structure exists: '../data/pdb_files/pdb9dpc.ent'
Lade PDB 9dru herunter...
Structure exists: '../data/pdb_files/pdb9dru.ent'
Lade PDB 9ds1 herunter...
Structure exists: '../data/pdb_files/pdb9ds1.ent'
Lade PDB 9mer herunter...
Structure exists: '../data/pdb_files/pdb9mer.ent'
Lade PDB 9mev herunter...
Structure exists: '../data/pdb_files/pdb9mev.ent'
Lade PDB 8rmx herunter...
Structure exists: '../data/pdb_files/pdb8rmx.ent'
Lade PDB 8rmy herunter...
Structure exists: '../data/pdb_files/pdb8rmy.ent'
Lade PDB 8ykt herunter...
Structure exists: '../data/pdb_files/pdb8ykt.ent'
Lade PDB 9azr herunter...
Structure exists: '../data/pdb_files/pdb9azr.ent'
Lade PDB 9azt herunter...
Structure exists: '../data/pdb_files/pdb9azt.ent'
Lade PDB 9bjg herunter...
Structure exists: '../data/pdb_files/pdb9bjg.ent'
Lade PDB 9bjh herunter...
Structure exists: '../data/pdb_files/pdb9bjh.ent'
Lade PDB 9cci herunter...
Structure exists: '../data/pdb_files/pdb9cci.ent'
Lade PDB 9ccj herunter...
Structure exists: '../data/pdb_files/pdb9ccj.ent'
Lade PDB 9bj2 herunter...
Structure exists: '../data/pdb_files/pdb9bj2.ent'
Lade PDB 8tmg herunter...
Structure exists: '../data/pdb_files/pdb8tmg.ent'
Lade PDB 8tmd herunter...
Structure exists: '../data/pdb_files/pdb8tmd.ent'
Lade PDB 8v13 herunter...
Structure exists: '../data/pdb_files/pdb8v13.ent'
Lade PDB 8y01 herunter...
Structure exists: '../data/pdb_files/pdb8y01.ent'
Lade PDB 8y3h herunter...
Structure exists: '../data/pdb_files/pdb8y3h.ent'
Lade PDB 8y3i herunter...
Structure exists: '../data/pdb_files/pdb8y3i.ent'
Lade PDB 8y3k herunter...
Structure exists: '../data/pdb_files/pdb8y3k.ent'
Lade PDB 8z4e herunter...
Structure exists: '../data/pdb_files/pdb8z4e.ent'
Lade PDB 8z6r herunter...
Structure exists: '../data/pdb_files/pdb8z6r.ent'
Lade PDB 8z6s herunter...
Structure exists: '../data/pdb_files/pdb8z6s.ent'
Lade PDB 8z6t herunter...
Structure exists: '../data/pdb_files/pdb8z6t.ent'
Lade PDB 8z6x herunter...
Structure exists: '../data/pdb_files/pdb8z6x.ent'
Lade PDB 9avo herunter...
Structure exists: '../data/pdb_files/pdb9avo.ent'
Lade PDB 9awe herunter...
Structure exists: '../data/pdb_files/pdb9awe.ent'
Lade PDB 9dm0 herunter...
Structure exists: '../data/pdb_files/pdb9dm0.ent'
Lade PDB 9dq3 herunter...
Structure exists: '../data/pdb_files/pdb9dq3.ent'
Lade PDB 9dq4 herunter...
Structure exists: '../data/pdb_files/pdb9dq4.ent'
Lade PDB 9gox herunter...
Structure exists: '../data/pdb_files/pdb9gox.ent'
Lade PDB 9goy herunter...
Structure exists: '../data/pdb_files/pdb9goy.ent'
Lade PDB 9k26 herunter...
Structure exists: '../data/pdb_files/pdb9k26.ent'
Lade PDB 9k27 herunter...
Structure exists: '../data/pdb_files/pdb9k27.ent'
Lade PDB 9mi6 herunter...
Structure exists: '../data/pdb_files/pdb9mi6.ent'
Lade PDB 8zhq herunter...
Structure exists: '../data/pdb_files/pdb8zhq.ent'
Lade PDB 8xml herunter...
Structure exists: '../data/pdb_files/pdb8xml.ent'
Lade PDB 8zr4 herunter...
Structure exists: '../data/pdb_files/pdb8zr4.ent'
Lade PDB 9l1s herunter...
Structure exists: '../data/pdb_files/pdb9l1s.ent'
Lade PDB 8sj4 herunter...
Structure exists: '../data/pdb_files/pdb8sj4.ent'
Lade PDB 8sja herunter...
Structure exists: '../data/pdb_files/pdb8sja.ent'
Lade PDB 8v9d herunter...
Structure exists: '../data/pdb_files/pdb8v9d.ent'
Lade PDB 8jef herunter...
Structure exists: '../data/pdb_files/pdb8jef.ent'
Lade PDB 8jkf herunter...
Structure exists: '../data/pdb_files/pdb8jkf.ent'
Lade PDB 8jqm herunter...
Structure exists: '../data/pdb_files/pdb8jqm.ent'
Lade PDB 8jqn herunter...
Structure exists: '../data/pdb_files/pdb8jqn.ent'
Lade PDB 8v5q herunter...
Structure exists: '../data/pdb_files/pdb8v5q.ent'
Lade PDB 8v5v herunter...
Structure exists: '../data/pdb_files/pdb8v5v.ent'
Lade PDB 8v91 herunter...
Structure exists: '../data/pdb_files/pdb8v91.ent'
Lade PDB 8vc7 herunter...
Structure exists: '../data/pdb_files/pdb8vc7.ent'
Lade PDB 9b3k herunter...
Structure exists: '../data/pdb_files/pdb9b3k.ent'
Lade PDB 9ekf herunter...
Structure exists: '../data/pdb_files/pdb9ekf.ent'
Lade PDB 8jkh herunter...
Structure exists: '../data/pdb_files/pdb8jkh.ent'
Lade PDB 8jqs herunter...
Structure exists: '../data/pdb_files/pdb8jqs.ent'
Lade PDB 8y31 herunter...
Structure exists: '../data/pdb_files/pdb8y31.ent'
Lade PDB 9b2w herunter...
Structure exists: '../data/pdb_files/pdb9b2w.ent'
Lade PDB 9dh2 herunter...
Structure exists: '../data/pdb_files/pdb9dh2.ent'
Lade PDB 9dwe herunter...
Structure exists: '../data/pdb_files/pdb9dwe.ent'
Lade PDB 8jei herunter...
Structure exists: '../data/pdb_files/pdb8jei.ent'
Lade PDB 9c44 herunter...
Structure exists: '../data/pdb_files/pdb9c44.ent'
Lade PDB 9ivk herunter...
Structure exists: '../data/pdb_files/pdb9ivk.ent'
Lade PDB 9dx6 herunter...
Structure exists: '../data/pdb_files/pdb9dx6.ent'
Lade PDB 8r40 herunter...
Structure exists: '../data/pdb_files/pdb8r40.ent'
Lade PDB 8ulj herunter...
Structure exists: '../data/pdb_files/pdb8ulj.ent'
Lade PDB 8vgn herunter...
Structure exists: '../data/pdb_files/pdb8vgn.ent'
Lade PDB 8vgo herunter...
Structure exists: '../data/pdb_files/pdb8vgo.ent'
Lade PDB 8ywq herunter...
Structure exists: '../data/pdb_files/pdb8ywq.ent'
Lade PDB 8vgh herunter...
Structure exists: '../data/pdb_files/pdb8vgh.ent'
Lade PDB 8vgi herunter...
Structure exists: '../data/pdb_files/pdb8vgi.ent'
Lade PDB 8vgj herunter...
Structure exists: '../data/pdb_files/pdb8vgj.ent'
Lade PDB 8vgk herunter...
Structure exists: '../data/pdb_files/pdb8vgk.ent'
Lade PDB 8vgp herunter...
Structure exists: '../data/pdb_files/pdb8vgp.ent'
Lade PDB 8xgo herunter...
Structure exists: '../data/pdb_files/pdb8xgo.ent'
Lade PDB 8xgs herunter...
Structure exists: '../data/pdb_files/pdb8xgs.ent'
Lade PDB 8xgu herunter...
Structure exists: '../data/pdb_files/pdb8xgu.ent'
Lade PDB 8s6m herunter...
Structure exists: '../data/pdb_files/pdb8s6m.ent'
Lade PDB 9gwt herunter...
Structure exists: '../data/pdb_files/pdb9gwt.ent'
Lade PDB 8wpw herunter...
Structure exists: '../data/pdb_files/pdb8wpw.ent'
Lade PDB 9atm herunter...
Structure exists: '../data/pdb_files/pdb9atm.ent'
Lade PDB 9au1 herunter...
Structure exists: '../data/pdb_files/pdb9au1.ent'
Lade PDB 8vdl herunter...
Structure exists: '../data/pdb_files/pdb8vdl.ent'
Lade PDB 8vqd herunter...
Structure exists: '../data/pdb_files/pdb8vqd.ent'
Lade PDB 8vsj herunter...
Structure exists: '../data/pdb_files/pdb8vsj.ent'
Lade PDB 9iqt herunter...
Structure exists: '../data/pdb_files/pdb9iqt.ent'
Lade PDB 8wfh herunter...
Structure exists: '../data/pdb_files/pdb8wfh.ent'
Lade PDB 8zps herunter...
Structure exists: '../data/pdb_files/pdb8zps.ent'
Lade PDB 8zpt herunter...
Structure exists: '../data/pdb_files/pdb8zpt.ent'
Lade PDB 9cj7 herunter...
Structure exists: '../data/pdb_files/pdb9cj7.ent'
Lade PDB 8tx3 herunter...
Structure exists: '../data/pdb_files/pdb8tx3.ent'
Lade PDB 8vyn herunter...
Structure exists: '../data/pdb_files/pdb8vyn.ent'
Lade PDB 9jbq herunter...
Structure exists: '../data/pdb_files/pdb9jbq.ent'
Lade PDB 8sow herunter...
Structure exists: '../data/pdb_files/pdb8sow.ent'
Lade PDB 8soz herunter...
Structure exists: '../data/pdb_files/pdb8soz.ent'
Lade PDB 8tbb herunter...
Structure exists: '../data/pdb_files/pdb8tbb.ent'
Lade PDB 8tft herunter...
Structure exists: '../data/pdb_files/pdb8tft.ent'
Lade PDB 8tuz herunter...
Structure exists: '../data/pdb_files/pdb8tuz.ent'
Lade PDB 8tv3 herunter...
Structure exists: '../data/pdb_files/pdb8tv3.ent'
Lade PDB 8kdm herunter...
Structure exists: '../data/pdb_files/pdb8kdm.ent'
Lade PDB 8keo herunter...
Structure exists: '../data/pdb_files/pdb8keo.ent'
Lade PDB 8kep herunter...
Structure exists: '../data/pdb_files/pdb8kep.ent'
Lade PDB 8ker herunter...
Structure exists: '../data/pdb_files/pdb8ker.ent'
Lade PDB 8u5l herunter...
Structure exists: '../data/pdb_files/pdb8u5l.ent'
Lade PDB 8sdh herunter...
Structure exists: '../data/pdb_files/pdb8sdh.ent'
Lade PDB 8vcr herunter...
Structure exists: '../data/pdb_files/pdb8vcr.ent'
Lade PDB 8yww herunter...
Structure exists: '../data/pdb_files/pdb8yww.ent'
Lade PDB 8udz herunter...
Structure exists: '../data/pdb_files/pdb8udz.ent'
Lade PDB 8q5y herunter...
Structure exists: '../data/pdb_files/pdb8q5y.ent'
Lade PDB 8rz0 herunter...
Structure exists: '../data/pdb_files/pdb8rz0.ent'
Lade PDB 8rz1 herunter...
Structure exists: '../data/pdb_files/pdb8rz1.ent'
Lade PDB 8rz2 herunter...
Structure exists: '../data/pdb_files/pdb8rz2.ent'
Lade PDB 8vvk herunter...
Structure exists: '../data/pdb_files/pdb8vvk.ent'
Lade PDB 8xse herunter...
Structure exists: '../data/pdb_files/pdb8xse.ent'
Lade PDB 8xsf herunter...
Structure exists: '../data/pdb_files/pdb8xsf.ent'
Lade PDB 8xsi herunter...
Structure exists: '../data/pdb_files/pdb8xsi.ent'
Lade PDB 8xsj herunter...
Structure exists: '../data/pdb_files/pdb8xsj.ent'
Lade PDB 8pn0 herunter...
Downloading PDB structure '8pn0'...
Desired structure doesn't exist
Lade PDB 8pmz herunter...
Structure exists: '../data/pdb_files/pdb8pmz.ent'
Lade PDB 8vui herunter...
Structure exists: '../data/pdb_files/pdb8vui.ent'
Lade PDB 8vvm herunter...
Structure exists: '../data/pdb_files/pdb8vvm.ent'
Lade PDB 8xqo herunter...
Structure exists: '../data/pdb_files/pdb8xqo.ent'
Lade PDB 8xqt herunter...
Structure exists: '../data/pdb_files/pdb8xqt.ent'
Lade PDB 8yky herunter...
Downloading PDB structure '8yky'...
Desired structure doesn't exist
Lade PDB 8zqe herunter...
Structure exists: '../data/pdb_files/pdb8zqe.ent'
Lade PDB 8y6a herunter...
Structure exists: '../data/pdb_files/pdb8y6a.ent'
Lade PDB 8tv1 herunter...
Structure exists: '../data/pdb_files/pdb8tv1.ent'
Lade PDB 8txp herunter...
Structure exists: '../data/pdb_files/pdb8txp.ent'
Lade PDB 8c0y herunter...
Structure exists: '../data/pdb_files/pdb8c0y.ent'
Lade PDB 8qh0 herunter...
Structure exists: '../data/pdb_files/pdb8qh0.ent'
Lade PDB 8qh1 herunter...
Structure exists: '../data/pdb_files/pdb8qh1.ent'
Lade PDB 8rp8 herunter...
Structure exists: '../data/pdb_files/pdb8rp8.ent'
Lade PDB 8rpb herunter...
Structure exists: '../data/pdb_files/pdb8rpb.ent'
Lade PDB 8ts0 herunter...
Structure exists: '../data/pdb_files/pdb8ts0.ent'
Lade PDB 8u31 herunter...
Structure exists: '../data/pdb_files/pdb8u31.ent'
Lade PDB 8u32 herunter...
Structure exists: '../data/pdb_files/pdb8u32.ent'
Lade PDB 8urf herunter...
Structure exists: '../data/pdb_files/pdb8urf.ent'
Lade PDB 8wz2 herunter...
Structure exists: '../data/pdb_files/pdb8wz2.ent'
Lade PDB 8hlc herunter...
Structure exists: '../data/pdb_files/pdb8hlc.ent'
Lade PDB 8hld herunter...
Structure exists: '../data/pdb_files/pdb8hld.ent'
Lade PDB 8p5m herunter...
Downloading PDB structure '8p5m'...
Desired structure doesn't exist
Lade PDB 8pwv herunter...
Structure exists: '../data/pdb_files/pdb8pwv.ent'
Lade PDB 8pww herunter...
Structure exists: '../data/pdb_files/pdb8pww.ent'
Lade PDB 8r9y herunter...
Structure exists: '../data/pdb_files/pdb8r9y.ent'
Lade PDB 8r9z herunter...
Structure exists: '../data/pdb_files/pdb8r9z.ent'
Lade PDB 8tzw herunter...
Structure exists: '../data/pdb_files/pdb8tzw.ent'
Lade PDB 8u03 herunter...
Structure exists: '../data/pdb_files/pdb8u03.ent'
Lade PDB 8u08 herunter...
Structure exists: '../data/pdb_files/pdb8u08.ent'
Lade PDB 8v2e herunter...
Structure exists: '../data/pdb_files/pdb8v2e.ent'
Lade PDB 8v4f herunter...
Structure exists: '../data/pdb_files/pdb8v4f.ent'
Lade PDB 8wsn herunter...
Structure exists: '../data/pdb_files/pdb8wsn.ent'
Lade PDB 8wsp herunter...
Structure exists: '../data/pdb_files/pdb8wsp.ent'
Lade PDB 8x0y herunter...
Structure exists: '../data/pdb_files/pdb8x0y.ent'
Lade PDB 8jin herunter...
Structure exists: '../data/pdb_files/pdb8jin.ent'
Lade PDB 8uwl herunter...
Structure exists: '../data/pdb_files/pdb8uwl.ent'
Lade PDB 8v6u herunter...
Structure exists: '../data/pdb_files/pdb8v6u.ent'
Lade PDB 8c2r herunter...
Structure exists: '../data/pdb_files/pdb8c2r.ent'
Lade PDB 8jpn herunter...
Structure exists: '../data/pdb_files/pdb8jpn.ent'
Lade PDB 8ut3 herunter...
Structure exists: '../data/pdb_files/pdb8ut3.ent'
Lade PDB 8yx1 herunter...
Structure exists: '../data/pdb_files/pdb8yx1.ent'
Lade PDB 8yx9 herunter...
Structure exists: '../data/pdb_files/pdb8yx9.ent'
Lade PDB 8k3c herunter...
Structure exists: '../data/pdb_files/pdb8k3c.ent'
Lade PDB 8ruu herunter...
Structure exists: '../data/pdb_files/pdb8ruu.ent'
Lade PDB 8xi6 herunter...
Structure exists: '../data/pdb_files/pdb8xi6.ent'
Lade PDB 8khc herunter...
Structure exists: '../data/pdb_files/pdb8khc.ent'
Lade PDB 8uky herunter...
Structure exists: '../data/pdb_files/pdb8uky.ent'
Lade PDB 8v52 herunter...
Structure exists: '../data/pdb_files/pdb8v52.ent'
Lade PDB 8j6i herunter...
Structure exists: '../data/pdb_files/pdb8j6i.ent'
Lade PDB 8r4o herunter...
Structure exists: '../data/pdb_files/pdb8r4o.ent'
Lade PDB 8r4q herunter...
Structure exists: '../data/pdb_files/pdb8r4q.ent'
Lade PDB 8r4u herunter...
Structure exists: '../data/pdb_files/pdb8r4u.ent'
Lade PDB 8u1c herunter...
Structure exists: '../data/pdb_files/pdb8u1c.ent'
Lade PDB 8vye herunter...
Downloading PDB structure '8vye'...
Desired structure doesn't exist
Lade PDB 8w0v herunter...
Structure exists: '../data/pdb_files/pdb8w0v.ent'
Lade PDB 8w0w herunter...
Structure exists: '../data/pdb_files/pdb8w0w.ent'
Lade PDB 8sxp herunter...
Structure exists: '../data/pdb_files/pdb8sxp.ent'
Lade PDB 8tbq herunter...
Structure exists: '../data/pdb_files/pdb8tbq.ent'
Lade PDB 8r1c herunter...
Structure exists: '../data/pdb_files/pdb8r1c.ent'
Lade PDB 8r1d herunter...
Structure exists: '../data/pdb_files/pdb8r1d.ent'
Lade PDB 8sdf herunter...
Structure exists: '../data/pdb_files/pdb8sdf.ent'
Lade PDB 8sdg herunter...
Structure exists: '../data/pdb_files/pdb8sdg.ent'
Lade PDB 8siq herunter...
Structure exists: '../data/pdb_files/pdb8siq.ent'
Lade PDB 8sit herunter...
Structure exists: '../data/pdb_files/pdb8sit.ent'
Lade PDB 8gat herunter...
Structure exists: '../data/pdb_files/pdb8gat.ent'
Lade PDB 8gav herunter...
Structure exists: '../data/pdb_files/pdb8gav.ent'
Lade PDB 8jel herunter...
Structure exists: '../data/pdb_files/pdb8jel.ent'
Lade PDB 8jen herunter...
Structure exists: '../data/pdb_files/pdb8jen.ent'
Lade PDB 8jeo herunter...
Structure exists: '../data/pdb_files/pdb8jeo.ent'
Lade PDB 8cin herunter...
Structure exists: '../data/pdb_files/pdb8cin.ent'
Lade PDB 8cbf herunter...
Structure exists: '../data/pdb_files/pdb8cbf.ent'
Lade PDB 8kfx herunter...
Structure exists: '../data/pdb_files/pdb8kfx.ent'
Lade PDB 8i5l herunter...
Structure exists: '../data/pdb_files/pdb8i5l.ent'
Lade PDB 8hp9 herunter...
Structure exists: '../data/pdb_files/pdb8hp9.ent'
Lade PDB 8hpq herunter...
Structure exists: '../data/pdb_files/pdb8hpq.ent'
Lade PDB 8hpv herunter...
Structure exists: '../data/pdb_files/pdb8hpv.ent'
Lade PDB 8the herunter...
Downloading PDB structure '8the'...
Desired structure doesn't exist
Lade PDB 8j24 herunter...
Structure exists: '../data/pdb_files/pdb8j24.ent'
Lade PDB 8jnk herunter...
Structure exists: '../data/pdb_files/pdb8jnk.ent'
Lade PDB 8tm1 herunter...
Structure exists: '../data/pdb_files/pdb8tm1.ent'
Lade PDB 8j6j herunter...
Structure exists: '../data/pdb_files/pdb8j6j.ent'
Lade PDB 8jgb herunter...
Structure exists: '../data/pdb_files/pdb8jgb.ent'
Lade PDB 8jgf herunter...
Structure exists: '../data/pdb_files/pdb8jgf.ent'
Lade PDB 8jgg herunter...
Structure exists: '../data/pdb_files/pdb8jgg.ent'
Lade PDB 8ija herunter...
Structure exists: '../data/pdb_files/pdb8ija.ent'
Lade PDB 7y3n herunter...
Structure exists: '../data/pdb_files/pdb7y3n.ent'
Lade PDB 7y3o herunter...
Structure exists: '../data/pdb_files/pdb7y3o.ent'
Lade PDB 8b7h herunter...
Structure exists: '../data/pdb_files/pdb8b7h.ent'
Lade PDB 8fja herunter...
Structure exists: '../data/pdb_files/pdb8fja.ent'
Lade PDB 8g4p herunter...
Structure exists: '../data/pdb_files/pdb8g4p.ent'
Lade PDB 8hn8 herunter...
Structure exists: '../data/pdb_files/pdb8hn8.ent'
Lade PDB 8hoc herunter...
Structure exists: '../data/pdb_files/pdb8hoc.ent'
Lade PDB 8hpf herunter...
Structure exists: '../data/pdb_files/pdb8hpf.ent'
Lade PDB 8hpu herunter...
Structure exists: '../data/pdb_files/pdb8hpu.ent'
Lade PDB 8hq7 herunter...
Structure exists: '../data/pdb_files/pdb8hq7.ent'
Lade PDB 8hrd herunter...
Structure exists: '../data/pdb_files/pdb8hrd.ent'
Lade PDB 8f38 herunter...
Structure exists: '../data/pdb_files/pdb8f38.ent'
Lade PDB 8r8d herunter...
Structure exists: '../data/pdb_files/pdb8r8d.ent'
Lade PDB 8ek5 herunter...
Structure exists: '../data/pdb_files/pdb8ek5.ent'
Lade PDB 8hws herunter...
Structure exists: '../data/pdb_files/pdb8hws.ent'
Lade PDB 8hwt herunter...
Structure exists: '../data/pdb_files/pdb8hwt.ent'
Lade PDB 8tui herunter...
Structure exists: '../data/pdb_files/pdb8tui.ent'
Lade PDB 8ucd herunter...
Structure exists: '../data/pdb_files/pdb8ucd.ent'
Lade PDB 8bk2 herunter...
Structure exists: '../data/pdb_files/pdb8bk2.ent'
Lade PDB 8hnl herunter...
Structure exists: '../data/pdb_files/pdb8hnl.ent'
Lade PDB 8hnm herunter...
Structure exists: '../data/pdb_files/pdb8hnm.ent'
Lade PDB 8t9z herunter...
Structure exists: '../data/pdb_files/pdb8t9z.ent'
Lade PDB 8trs herunter...
Structure exists: '../data/pdb_files/pdb8trs.ent'
Lade PDB 8trt herunter...
Structure exists: '../data/pdb_files/pdb8trt.ent'
Lade PDB 8w8b herunter...
Structure exists: '../data/pdb_files/pdb8w8b.ent'
Lade PDB 8wsq herunter...
Structure exists: '../data/pdb_files/pdb8wsq.ent'
Lade PDB 8w83 herunter...
Structure exists: '../data/pdb_files/pdb8w83.ent'
Lade PDB 8w85 herunter...
Structure exists: '../data/pdb_files/pdb8w85.ent'
Lade PDB 8w86 herunter...
Structure exists: '../data/pdb_files/pdb8w86.ent'
Lade PDB 8bg1 herunter...
Structure exists: '../data/pdb_files/pdb8bg1.ent'
Lade PDB 8bg2 herunter...
Structure exists: '../data/pdb_files/pdb8bg2.ent'
Lade PDB 8bg3 herunter...
Structure exists: '../data/pdb_files/pdb8bg3.ent'
Lade PDB 8bg4 herunter...
Structure exists: '../data/pdb_files/pdb8bg4.ent'
Lade PDB 8bg5 herunter...
Structure exists: '../data/pdb_files/pdb8bg5.ent'
Lade PDB 8ez3 herunter...
Structure exists: '../data/pdb_files/pdb8ez3.ent'
Lade PDB 8ez7 herunter...
Structure exists: '../data/pdb_files/pdb8ez7.ent'
Lade PDB 8ez8 herunter...
Structure exists: '../data/pdb_files/pdb8ez8.ent'
Lade PDB 8hes herunter...
Structure exists: '../data/pdb_files/pdb8hes.ent'
Lade PDB 8ttw herunter...
Structure exists: '../data/pdb_files/pdb8ttw.ent'
Lade PDB 8w84 herunter...
Structure exists: '../data/pdb_files/pdb8w84.ent'
Lade PDB 8bec herunter...
Structure exists: '../data/pdb_files/pdb8bec.ent'
Lade PDB 8g05 herunter...
Structure exists: '../data/pdb_files/pdb8g05.ent'
Lade PDB 8hgl herunter...
Structure exists: '../data/pdb_files/pdb8hgl.ent'
Lade PDB 8tpa herunter...
Structure exists: '../data/pdb_files/pdb8tpa.ent'
Lade PDB 8oxv herunter...
Structure exists: '../data/pdb_files/pdb8oxv.ent'
Lade PDB 8oxw herunter...
Structure exists: '../data/pdb_files/pdb8oxw.ent'
Lade PDB 8oxx herunter...
Structure exists: '../data/pdb_files/pdb8oxx.ent'
Lade PDB 8oxy herunter...
Structure exists: '../data/pdb_files/pdb8oxy.ent'
Lade PDB 8f5i herunter...
Structure exists: '../data/pdb_files/pdb8f5i.ent'
Lade PDB 8fdo herunter...
Structure exists: '../data/pdb_files/pdb8fdo.ent'
Lade PDB 8tp5 herunter...
Structure exists: '../data/pdb_files/pdb8tp5.ent'
Lade PDB 8tp7 herunter...
Structure exists: '../data/pdb_files/pdb8tp7.ent'
Lade PDB 8gy5 herunter...
Structure exists: '../data/pdb_files/pdb8gy5.ent'
Lade PDB 8s9g herunter...
Structure exists: '../data/pdb_files/pdb8s9g.ent'
Lade PDB 8euu herunter...

In [51]:
#cluster VL and VH

In [52]:
df_cleaned

,pdb,Hchain,Lchain,antigen_species,heavy_subclass,light_subclass,antigen_type,antigen_name,organism,resolution,light_ctype
3,8uzp,H,L,mus musculus,IGHV1,IGLV1,protein,stem_mimetic_01,Homo sapiens; Mus musculus,2.711,Lambda
4,8uzp,A,B,mus musculus,IGHV1,IGLV1,protein,stem_mimetic_01,Homo sapiens; Mus musculus,2.711,Lambda
5,8veb,G,I,influenza a virus,IGHV4,IGKV1,protein,hemagglutinin,Homo sapiens; Influenza A virus,2.970,Kappa
6,8veb,H,L,influenza a virus,IGHV4,IGKV1,protein,hemagglutinin,Homo sapiens; Influenza A virus,2.970,Kappa
8,8ved,H,L,influenza a virus,IGHV4,IGKV2,protein,hemagglutinin,Homo sapiens; Influenza A virus,2.980,Kappa
...,...,...,...,...,...,...,...,...,...,...,...
5517,3q1s,H,L,homo sapiens,IGHV4,IGKV3D,protein,interleukin-22,HOMO SAPIENS,2.150,Kappa
5518,4zfg,H,L,homo sapiens,IGHV3,IGKV1,protein,angiopoietin-2,HOMO SAPIENS,2.270,Kappa
5519,5sy8,H,L,synthetic construct,IGHV3,IGLV3,protein,10e8 epitope scaffold t117v2,HOMO SAPIENS; SYNTHETIC CONSTRUCT,1.620,Lambda
5520,3idx,H,L,human immunodeficiency virus 1,IGHV3,IGKV1,protein,hiv-1 hxbc2 gp120 core,HUMAN IMMUNODEFICIENCY VIRUS 1; HOMO SAPIENS,2.500,Kappa
5521,4ps4,H,L,homo sapiens,IGHV2,IGKV3D,protein,interleukin-13,HOMO SAPIENS,2.800,Kappa

In [ ]:
df_clean